### ISSUE TITLE
Staking events for slash appears to be quite old

### ISSUE THREAD

**Issue by Mitchell-Grimes** [polkascan/polkascan-explorer-gui#17]
Location: https://polkascan.io/pre/kusama/event?module=staking&event=Slash&page=1

![image](https://user-images.githubusercontent.com/52660893/80528945-b97e0480-8964-11ea-98a9-6ae21faf0fcf.png)

Blocks appear to be fairly far back for slashing events. Are events for slashing where governance deferred them not something that shows up here?

**Comment by emielvanderhoek** [comment]
Indeed now slashes have taken place.
